---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull subhodip703/otms-backend:latest
    
    - name: Run Docker container
      shell: docker run -d -p 8081:8080 subhodip703/otms-backend:latest
